### ISSUE TITLE
how do add to kotlin application?

### ISSUE THREAD

**Issue by aadog** [c-fraser/deferred#1]
how do add to kotlin application?

**Comment by c-fraser** [comment]
> how do add to kotlin application?

Apply the [gradle plugin](https://github.com/c-fraser/deferred/tree/main/deferred-gradle-plugin) to your project as demonstrated in the [usage documentation](https://github.com/c-fraser/deferred#usage).

**Comment by aadog** [comment]
It seems that he doesn't work Maven Central's problem?
